export const qiitaTags = [
  { value: '個人開発', label: '個人開発' },
  { value: 'Ruby/Rails', label: 'Ruby/Rails' },
  { value: 'JavaScript', label: 'JavaScript' },
  { value: 'TypeScript', label: 'TypeScript' },
  { value: 'React', label: 'React' },
  { value: 'Next.js', label: 'Next.js' },
  { value: 'Vue.js', label: 'Vue.js' },
  { value: 'Vuetify', label: 'Vuetify' },
  { value: 'Nuxt.js', label: 'Nuxt.js' },
  { value: 'Stumulus', label: 'Stumulus' },
  { value: 'Laravel', label: 'Laravel' },
  { value: 'Python', label: 'Python' },
  { value: 'Flutter', label: 'Flutter' },
  { value: 'Googleログイン', label: 'Googleログイン' },
  { value: 'LINEログイン', label: 'LINEログイン' },
  { value: 'LINEbot', label: 'LINEbot' },
  { value: 'LIFF', label: 'LIFF' },
  { value: 'TwitterAPI', label: 'TwitterAPI' },
  { value: 'SlackAPI', label: 'SlackAPI' },
  { value: 'DiscordAPI', label: 'DiscordAPI' },
  { value: 'GitHubGraphQLAPI', label: 'GitHubGraphQLAPI' },
  { value: 'YouTubeDataAPI', label: 'YouTubeDataAPI' },
  { value: 'iTunesAPI', label: 'iTunesAPI' },
  { value: 'SpotifyAPI', label: 'SpotifyAPI' },
  { value: 'PokeAPI', label: 'PokeAPI' },
  { value: 'RakutenAPI', label: 'RakutenAPI' },
  { value: 'WebSpeechAPI', label: 'WebSpeechAPI' },
  { value: 'SpeechToTextAPI', label: 'SpeechToTextAPI' },
  { value: '図書館API', label: '図書館API' },
  { value: 'GoogleooksAIs', label: 'GoogleBooksAPIs' },
  { value: 'GoogleMapsAPI', label: 'GoogleMapsAPI' },
  { value: 'GooglePlacesAPI', label: 'GooglePlacesAPI' },
  { value: 'GoogleCloudVisionAPI', label: 'GoogleCloudVisionAPI' },
  { value: 'GoogleCalendar', label: 'GoogleCalendar' },
  { value: 'OpenAI API', label: 'OpenAI API' },
  { value: '画像生成AI', label: '画像生成AI' },
  {
    value: 'MicrosoftSpeakerRecognitionAPI',
    label: 'MicrosoftSpeakerRecognitionAPI',
  },
  { value: 'Chrome拡張', label: 'Chrome拡張' },
  { value: '自作gem', label: '自作gem' },
  { value: '形態素解析', label: '形態素解析' },
  { value: 'TensorFlow', label: 'TensorFlow' },
  { value: 'Amazon Comprehend', label: 'Amazon Comprehend' },
  { value: 'Design', label: 'Design' },
  { value: 'Cloudinary', label: 'Cloudinary' },
  { value: 'Firebase', label: 'Firebase' },
  { value: 'Netlify', label: 'Netlify' },
  { value: 'Heroku', label: 'Heroku' },
  { value: 'AWS', label: 'AWS' },
  { value: 'Docker', label: 'Docker' },
  { value: 'クソアプリ', label: 'クソアプリ' },
  { value: '転職,ポエム', label: '転職,ポエム' },
];
